name: LucianoTeste
favicon: null
layout_spectrum: 0.69207
typography_spectrum: 0.00543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#686e64'
    - '#a2a2a2'
    - '#d6d6d6'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
